abhisharma404/vault

src/colors.py
src/crawler.py
src/crawler/main.py
src/info_gathering/header_vuln.py
src/main.py
src/network_scanner/network_scanner.py
src/network_scanner/oop_network_scanner_demo.py
src/scanner.py
src/ssl_scanner/ssl_scanner.py
src/type.py
src/vault.py

Fixes #5 
I have fixed the PEP-8 issue. Please let me know if I missed something.
Also what kind of documentation is needed for this. A bit of guideline would be helpful.

Reformatted code according to PEP-8 style

---

src/lib/info_gathering/header_vuln.py
src/lib/ssl_scanner/ssl_scanner.py
src/lib/website_scanner/xss/scanner.py
src/lib/website_scanner/xss/xss.py
src/vault.py

Fix pep8 and remove unused imports

---

src/payloads/xss_payloads.txt

Fixes #20.
All the payloads are taken from https://github.com/Pgaijin66/XSS-Payloads.
OS: Manjaro

Add XSS payloads

---

src/vault.py

Add check for URL parsing

---

src/vault.py

This change will use colors module for displaying error lines.After commiting the changes the error lines will be displayed in red color.
OS: x
Python Version: x

Fixed color for error lines

---

src/logger.py
src/vault.py

Fixes #1.
This will add a new logger to vault scanner. I haven't connected the logger with any code. we can do it once you are done with the final touchups :)

Add logger

---

src/vault.py

Fixes #29 
Accepted ip addresses:
- 127.0.0.1
- 192.168.1.1
- 192.168.1.255
- 255.255.255.255
- 0.0.0.0
Rejects ip addresses such as:
- 192.168
- 192.168.1.256
- 1...1
OS: x
Python Version: 3.6.7

IP validation

---

requirements.txt
src/lib/whois_lookup/__init__.py
src/lib/whois_lookup/lookup.py
src/vault.py

Added a check for simple whois lookup.
Also updated the requirements.txt file for new package i.e ipwhois
OS: Manjaro

Add check for Whois lookup

---

src/lib/info_gathering/header_vuln.py
src/lib/ssl_scanner/ssl_scanner.py
src/vault.py

Created Output function for SSL module.
OS: Ubuntu 18.10
Python Version: 3.6.7

SSL output

---

src/lib/info_gathering/header_vuln.py
src/vault.py

OS: Ubuntu 18.10
Python Version: 3.6.7

info-output-function

---

src/lib/info_gathering/finding_comment.py
src/vault.py

Comment output function added
OS: x
Python Version: x

comment-output

---

src/dorker.py
src/vault.py

Output function for whois and dorks, fixed dorks module
OS: Ubuntu 18.10
Python Version: 3.6.7

whois, dork output

---

src/vault.py

Fixes #46 
Also fixed some small pep8 issues
OS: Manjaro

Add option to run all the scan at once

---

src/vault.py

OS: Linux
Python Version: 3.6.5

Perform IP start and end range validation

---

README.md
src/lib/others/info_gathering/finder/finding_email.py
src/vault.py

Email finder

---

README.md
requirements.txt
src/lib/utilities/keylogger/keylogger.py
src/vault.py

This pull request implements a keylogger that register keystrokes using the multi-plataform pynput library. Then, the keylogger sends the keystrokes by email.
Usage: python vault.py -keylogger - interval <INTERVAL> -sender <SENDER> -destination <DESTINATION> -host <HOST> -p <PORT> -username <USERNAME> -password <PASSWORD>
Where:
- INTERVAL: Number of seconds to send the email with the registered keystrokes.
- SENDER: Email to send to
- HOST: SMTP Host to use
- PORT: Port to connect to the SMTP server
- USERNAME: Username to login into the SMTP server
- PASSWORD: Password to login into the SMTP server
OS: Linux

Implement a keylogger

---

README.md
src/lib/others/info_gathering/jquery_check.py
src/vault.py

Implement jQuery version checking and get a list of the possible vulnerabilities
OS: Linux
Fixes #52

Implement jQuery version checking

---

README.md
src/lib/attacks/ping_death/ping_death.py
src/vault.py

Implement ping of death

---

src/vault.py

Check if port scanner is started with sudo or not

---

src/lib/others/detect_cms/detect_cms.py

Improve CMS Detection

---

src/lib/others/detect_honeypots/honeypots.py
src/vault.py

Add honeypot detection functionality

---

src/lib/attacks/arp_spoof/arp_spoofer.py
src/lib/others/detect_honeypots/honeypots.py
src/lib/others/info_gathering/header_vuln.py
src/lib/scanner/hash_scanner/hash_scanner.py
src/lib/utilities/mac_changer/mac_changer.py
src/vault.py

Make PEP 8 changes in the project. Remove an unused line of the parser
on vault.py
OS: Linux

Make PEP 8 Changes and fix vault.py

---

docs/CODE_OF_CONDUCT.rst
docs/CONTRIBUTING.rst
docs/INSTALL.rst
docs/LICENSE.rst
docs/Makefile
docs/PARAMETERS.rst
docs/conf.py
docs/index.rst
docs/make.bat
docs/quick-start.rst

This will add documentation for Vault and all the related files so they can be hosted on readthedocs.
OS: Manjaro

Add documentation for vault

---

docs/PARAMETERS.rst

Fixed typo in documentation.
OS: Manjaro

Fix typo in documentation

---

src/vault.py

Ctrl+C handling applied 
OS: archlinux
Python Version: 3.7.3

Issue#94 handle sigint
